export const Products = [
  // {
  //   id: 1,
  //   name: "BISHANLAL BABULAL 3 No Bhujia asli Bikaneri Swad 500gm (Pack of 1)",
  //   price: 139,
  //   image1: "../assets/ProductImg/bb3Bhujia1.png",
  //   image2: "../assets/ProductImg/bb3Bhujia2.png",
  // },
  // {
  //   id: 2,
  //   name: "BISHANLAL BABULAL Aalu Bhujia asli Bikaneri Swad 500gm (Pack of 1)",
  //   price: 159,
  //   image1: "../assets/ProductImg/bbAalu1.png",
  //   image2: "../assets/ProductImg/bbAalu2.png",
  // },
  // {
  //   id: 3,
  //   name: "BISHANLAL BABULAL Bhujia asli Bikaneri Swad 500gm (Pack of 1)",
  //   price: 139,
  //   image1: "../assets/ProductImg/bbBhujiaB1.png",
  //   image2: "../assets/ProductImg/bbBhujiaB2.png",
  // },
  // {
  //   id: 4,
  //   name: "BISHANLAL BABULAL Karor Pati Bhujia asli Bikaneri Swad 500gm (Pack of 1)",
  //   price: 139,
  //   image1: "../assets/ProductImg/bbKaror1.png",
  //   image2: "../assets/ProductImg/bbKaror2.png",
  // },
  // {
  //   id: 5,
  //   name: "BISHANLAL BABULAL Papad asli Bikaneri Swad 500gm (Pack of 1)",
  //   price: 138,
  //   image1: "../assets/ProductImg/bbPapad1.png",
  //   image2: "../assets/ProductImg/bbPapad2.png",
  // },
  {
    id: 6,
    name: 'Hariram Ji 3 No. Bhujia Real Bikaneri Bhujia 400g (Pack Of 1)',
    price: 135,
    image1: '../assets/ProductImg/hr3Bhujiya1.png',
    image2: '../assets/ProductImg/hr3Bhujiya2.png',
  },
  {
    id: 7,
    name: 'Hariram Ji Barik Bhujia Real Bikaneri Bhujia 500g (Pack Of 1)',
    price: 135,
    image1: '../assets/ProductImg/hrBhujiyaB1.png',
    image2: '../assets/ProductImg/hrBhujiyaB2.png',
  },
  {
    id: 8,
    name: 'Hariram Ji Mota Bhujia Real Bikaneri Bhujia 500g (Pack Of 1)',
    price: 129,
    image1: '../assets/ProductImg/hrBhujiyaM1.png',
    image2: '../assets/ProductImg/hrBhujiyaM2.png',
  },
  {
    id: 9,
    name: 'Hariram Ji Special Badi 500 Gm',
    price: 120,
    image1: '../assets/ProductImg/hrBadi1.png',
    image2: '../assets/ProductImg/hrBadi1.png',
  },
  {
    id: 10,
    name: 'M4B Hdman Ji Mahin Bhujia Bikaneri Swad 500 Gm (Pack Of 1)',
    price: 139,
    image1: '../assets/ProductImg/hdBhujiyaB1.jpg',
    image2: '../assets/ProductImg/hdBhujiyaB1.jpg',
  },
  {
    id: 11,
    name: 'M4B Hdman Ji Mota Bhujia Bikaneri Swad 500 Gm (Pack Of 1)',
    price: 139,
    image1: '../assets/ProductImg/hdBhujiyaM1.jpg',
    image2: '../assets/ProductImg/hdBhujiyaM1.jpg',
  },
  {
    id: 12,
    name: 'Namkeen Kaju 200 Gm',
    price: 60,
    image1: '../assets/ProductImg/kaju.png',
    image2: '../assets/ProductImg/kaju.png',
  },
  // {
  //   id: 13,
  //   name: 'Rajasthani Badi 500gm',
  //   price: 98,
  //   image1: '../assets/ProductImg/rjBadi1.png',
  //   image2: '../assets/ProductImg/rjBadi2.png',
  // },
  {
    id: 14,
    name: 'Rajasthani Papad Urad-Moong Special 500gm',
    price: 125,
    image1: '../assets/ProductImg/rjPapad1.png',
    image2: '../assets/ProductImg/rjPapad2.png',
  },
  // {
  //   id: 15,
  //   name: 'Rajasthani Sangri (Dry) 250gm',
  //   price: 299,
  //   image1: '../assets/ProductImg/Sangri1.png',
  //   image2: '../assets/ProductImg/Sangri2.png',
  // },
  {
    id: 16,
    name: 'Teekha Masala Conflex 100 Gm',
    price: 25,
    image1: '../assets/ProductImg/namkin.png',
    image2: '../assets/ProductImg/namkin.png',
  },
];
